apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  labels:
    type: local
    {{- include "common.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.path }}
