apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
